# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint
    - right_shoulder_pan_joint
    - right_shoulder_lift_joint
    - right_elbow_joint
    - right_wrist_1_joint
    - right_wrist_2_joint
    - right_wrist_3_joint


# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 125

# gazebo_ros_control:
#   pid_gains:
#       left_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       left_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       left_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       left_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       left_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       left_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       right_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       right_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       right_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       right_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       right_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
#       right_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
pos_based_pos_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - left_shoulder_pan_joint
     - left_shoulder_lift_joint
     - left_elbow_joint
     - left_wrist_1_joint
     - left_wrist_2_joint
     - left_wrist_3_joint
   gains:
      #!!These values are useable, but maybe not optimal
      left_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      left_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      left_elbow_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5

# right arm pose controller
right_pos_based_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - right_shoulder_pan_joint
     - right_shoulder_lift_joint
     - right_elbow_joint
     - right_wrist_1_joint
     - right_wrist_2_joint
     - right_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      right_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      right_elbow_joint: {trajectory: 0.1, goal: 0.1}
      right_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      right_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      right_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10
   gains:
      #!!These values are useable, but maybe not optimal
      right_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5

# left arm pose controller
left_pos_based_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - left_shoulder_pan_joint
     - left_shoulder_lift_joint
     - left_elbow_joint
     - left_wrist_1_joint
     - left_wrist_2_joint
     - left_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      left_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      left_elbow_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10
   gains:
      #!!These values are useable, but maybe not optimal
      left_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5

# dual arm pose controller
dual_arm_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - left_shoulder_pan_joint
     - left_shoulder_lift_joint
     - left_elbow_joint
     - left_wrist_1_joint
     - left_wrist_2_joint
     - left_wrist_3_joint
     - right_shoulder_pan_joint
     - right_shoulder_lift_joint
     - right_elbow_joint
     - right_wrist_1_joint
     - right_wrist_2_joint
     - right_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      left_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      left_elbow_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
      right_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      right_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      right_elbow_joint: {trajectory: 0.1, goal: 0.1}
      right_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      right_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      right_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10
   gains:
      #!!These values are useable, but maybe not optimal
      left_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      right_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5

   
# Joint Trajectory Controller - velocity based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
vel_based_pos_traj_controller:
   type: velocity_controllers/JointTrajectoryController
   joints:
     - left_shoulder_pan_joint
     - left_shoulder_lift_joint
     - left_elbow_joint
     - left_wrist_1_joint
     - left_wrist_2_joint
     - left_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      left_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      left_elbow_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      left_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10
   gains:
      #!!These values are useable, but maybe not optimal
      left_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

   # state_publish_rate:  50 # Defaults to 50
   # action_monitor_rate: 20 # Defaults to 20
   #hold_trajectory_duration: 0 # Defaults to 0.5

my_vel_controller:
    type: robot_controllers/MyVelControllerPlugin
    joints:
     - left_shoulder_pan_joint
     - left_shoulder_lift_joint
     - left_elbow_joint
     - left_wrist_1_joint
     - left_wrist_2_joint
     - left_wrist_3_joint

my_cart_controller:
    type: robot_controllers/MyCartControllerPlugin
    joints:
     - left_shoulder_pan_joint
     - left_shoulder_lift_joint
     - left_elbow_joint
     - left_wrist_1_joint
     - left_wrist_2_joint
     - left_wrist_3_joint
    gains:
          #!!These values are useable, but maybe not optimal
          left_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}


gains:
      #!!These values are useable, but maybe not optimal
      left_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
      left_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

my_impedance_controller:
    type: robot_controllers/MyImpedanceControllerPlugin
    joints:
     - left_shoulder_pan_joint
     - left_shoulder_lift_joint
     - left_elbow_joint
     - left_wrist_1_joint
     - left_wrist_2_joint
     - left_wrist_3_joint
    gains:
          #!!These values are useable, but maybe not optimal
          left_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}

my_init_controller:
    type: robot_controllers/MyInitControllerPlugin
    joints:
     - left_shoulder_pan_joint
     - left_shoulder_lift_joint
     - left_elbow_joint
     - left_wrist_1_joint
     - left_wrist_2_joint
     - left_wrist_3_joint
    gains:
          #!!These values are useable, but maybe not optimal
          left_shoulder_pan_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_shoulder_lift_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_elbow_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_wrist_1_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_wrist_2_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
          left_wrist_3_joint: {p: 1.2,  i: 0.0, d: 0.1, i_clamp: 1}
